project:
  type: website

website:
  title: " "
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Accueil
      - href: finance.qmd
        text: Finance Quantitative
      - href: risque-regulation.qmd
        text: Risque & Régulation
      - href: data-science-ml.qmd
        text: Data Science & ML
      - href: articles-ressources.qmd
        text: Ressources
      - href: about.qmd
        text: À propos

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



