project:
  type: website
  output-dir: docs


website:
  title: " "
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Accueil
      - href: finance_quant/index.qmd
        text: Finance Quantitative
      - href: risques/index.qmd
        text: Risque & Régulation
      - href: modelisation-stat-data/index.qmd
        text: Modélisation stat & Data science
      - href: articles-ressources.qmd
        text: Ressources
      - href: about.qmd
        text: À propos

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



